### ISSUE TITLE
Cross-compilation issue for ppc architecture with gcc 4.7

### ISSUE THREAD

**Issue by ymartin59** [acoustid/chromaprint#43]
I am building [Chromaprint 1.4.2 as Synology package for SynoCommunity](https://github.com/SynoCommunity/spksrc/pull/2864) but compilation fails with DSM 5.2 `qoriq` toolchain (`qoriq-gcc4374_eglibc2874_qoriq-GPL.txz`):

```
make -f src/CMakeFiles/chromaprint_objs.dir/build.make src/CMakeFiles/chromaprint_objs.dir/build
make[5]: Entering directory '/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2'
/usr/bin/cmake -E cmake_progress_report /spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/CMakeFiles 2
[  5%] Building CXX object src/CMakeFiles/chromaprint_objs.dir/fft_lib_avfft.cpp.o
cd /spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src && /spksrc/toolchains/syno-qoriq-5.2/work/powerpc-none-linux-gnuspe/bin/powerpc-none-linux-gnuspe-g++   -DCHROMAPRINT_NODLL -DHAVE_CONFIG_H -D_SCL_SECURE_NO_WARNINGS -D_USE_MATH_DEFINES -D__STDC_CONSTANT_MACROS -D__STDC_LIMIT_MACROS -I/spksrc/toolchains/syno-qoriq-5.2/work/powerpc-none-linux-gnuspe/powerpc-none-linux-gnuspe/include -mcpu=8548 -mhard-float -mfloat-gprs=double -I/spksrc/spk/chromaprint/work-qoriq-5.2/install//usr/local/chromaprint/include   -Wall -O3 -DNDEBUG -I/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2 -I/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src -I/spksrc/spk/chromaprint/work-qoriq-5.2/install/usr/local/chromaprint/include    -o CMakeFiles/chromaprint_objs.dir/fft_lib_avfft.cpp.o -c /spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/fft_lib_avfft.cpp
In file included from /spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/fft_lib_avfft.h:14,
                 from /spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/fft_lib_avfft.cpp:4:
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/utils.h: In function 'void chromaprint::PrepareHammingWindow(RandomAccessIterator, RandomAccessIterator, double)':
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/utils.h:40: error: ISO C++ forbids declaration of 'size' with no type
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/utils.h: In function 'void chromaprint::ApplyWindow(InputIt, InputIt, WindowIt&, OutputIt&)':
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/utils.h:49: error: ISO C++ forbids declaration of 'input' with no type
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/utils.h:51: error: invalid type argument of 'unary *'
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/fft_lib_avfft.cpp: In member function 'void chromaprint::FFTLib::Load(const int16_t*, const int16_t*, const int16_t*, const int16_t*)':
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/fft_lib_avfft.cpp:27: error: ISO C++ forbids declaration of 'window' with no type
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/fft_lib_avfft.cpp:27: error: invalid conversion from 'FFTSample*' to 'int'
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/fft_lib_avfft.cpp:28: error: ISO C++ forbids declaration of 'output' with no type
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/fft_lib_avfft.cpp:28: error: invalid conversion from 'FFTSample*' to 'int'
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/fft_lib_avfft.cpp: In member function 'void chromaprint::FFTLib::Compute(chromaprint::FFTFrame&)':
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/fft_lib_avfft.cpp:35: error: ISO C++ forbids declaration of 'input' with no type
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/fft_lib_avfft.cpp:35: error: invalid conversion from 'FFTSample*' to 'int'
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/fft_lib_avfft.cpp:36: error: ISO C++ forbids declaration of 'output' with no type
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/fft_lib_avfft.cpp:36: error: cannot convert '__gnu_cxx::__normal_iterator<double*, std::vector<double, std::allocator<double> > >' to 'int' in initialization
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/fft_lib_avfft.cpp:37: error: invalid types 'int[int]' for array subscript
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/fft_lib_avfft.cpp:37: error: invalid types 'int[int]' for array subscript
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/fft_lib_avfft.cpp:37: error: invalid types 'int[int]' for array subscript
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/fft_lib_avfft.cpp:38: error: invalid types 'int[unsigned int]' for array subscript
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/fft_lib_avfft.cpp:38: error: invalid types 'int[int]' for array subscript
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/fft_lib_avfft.cpp:38: error: invalid types 'int[int]' for array subscript
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/fft_lib_avfft.cpp:42: error: invalid type argument of 'unary *'
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/fft_lib_avfft.cpp:42: error: invalid types 'int[int]' for array subscript
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/fft_lib_avfft.cpp:42: error: invalid types 'int[int]' for array subscript
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/fft_lib_avfft.cpp:42: error: invalid types 'int[int]' for array subscript
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/fft_lib_avfft.cpp:42: error: invalid types 'int[int]' for array subscript
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/utils.h: In function 'void chromaprint::ApplyWindow(InputIt, InputIt, WindowIt&, OutputIt&) [with InputIt = const int16_t*, WindowIt = int, OutputIt = int]':
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/fft_lib_avfft.cpp:29:   instantiated from here
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/utils.h:49: error: invalid conversion from 'const int16_t*' to 'int'
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/utils.h:50: error: ISO C++ forbids comparison between pointer and integer
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/utils.h:51: error: invalid type argument of 'unary *'
/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2/src/utils.h:51: error: invalid type argument of 'unary *'
src/CMakeFiles/chromaprint_objs.dir/build.make:54: recipe for target 'src/CMakeFiles/chromaprint_objs.dir/fft_lib_avfft.cpp.o' failed
make[5]: *** [src/CMakeFiles/chromaprint_objs.dir/fft_lib_avfft.cpp.o] Error 1
make[5]: Leaving directory '/spksrc/spk/chromaprint/work-qoriq-5.2/chromaprint-1.4.2'
```

Do you have any suggestion how to get chromaprint built with GCC 4.7 for ppc ?

**Comment by ymartin59** [comment]
Please notice chromaprint 1.4.2 probably builds with GCC 4.9 for pcc with DSM 6.1 toolchain `qoriq-gcc493_glibc220_hard_qoriq-GPL.txz`

**Comment by ymartin59** [comment]
OK. C++11 is required, backporting is too much work. I just gave up upgrading to 1.4.x
